customhost = "geddatabase.cavyhltr1yt8.us-east-1.rds.amazonaws.com"
customuser = "GEDuser"
custompass = "GEDuser123"
customdb = "GEDdatabase"
custombucket = "ningjoydaniel-bucket"
customregion = "us-east-1"
